### ISSUE TITLE
probably need 4 half days for this workshop

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/julia-for-hpc#55]
to have more time for exercises

**Comment by pojeda** [comment]
Something that could help is if we have some person from the support for the HPC cluster that we are using during the course. That person would take care quickly of the common issues (login, not uploaded keys, ...)

**Comment by wikfeldt** [comment]
actually i now think this should be split into two separate workshops! One "intro to Julia" and one "Julia for HPC". There's definitely enough material for it

**Comment by wikfeldt** [comment]
material is now split into julia-intro and julia-hpc, closing issue
