### ISSUE TITLE
try to generalise lesson by moving LUMI-specific things to setup episode

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/julia-for-hpc#79]
moreover, material from cluster.rst and hpc-cluster.rst should be merged

**Comment by jaantollander** [comment]
I think @code4yonglei remove the redundant `cluster.rst`.
I'm improving the `hpc-cluster.rst` section and LUMI specific setup at the moment.

**Comment by code4yonglei** [comment]
Yes, I have included the content in the cluster.rst to hpc-cluster.rst and other episodes.
