### ISSUE TITLE
LUMI does not have mpiexec/mpirun

### ISSUE THREAD

**Issue by ffrancesco94** [ENCCS/julia-for-hpc#83]
LUMI doesn't have any `mpiexec`/`mpirun`, nor an `OpenMPI` (well, it has one, but it is not really supported from what I can see) module. I tested yesterday using the CSC `julia-mpi` module and it seems to work, but we have to pass it all the slurm flags for it to work properly, unless `salloc` is called before. We also need to pass the number of tasks with `-n` rather than `-np` since it is `srun` that is called under the hood. I will submit a PR to fix this.

**Comment by code4yonglei** [comment]
@ffrancesco94 
check the MPI tutorial here: https://docs.csc.fi/support/tutorials/julia/#__tabbed_5_3

```
module use /appl/local/csc/modulefiles
module load julia
module load julia-mpi
julia --project=. -e 'using Pkg; Pkg.instantiate()'
julia --project=. script.jl
```

**Comment by ffrancesco94** [comment]
Yes, exactly. That's what I followed. I will update the workshop material with that.

**Comment by jaantollander** [comment]
I updated the LUMI environment modules and pushed updates to the LUMI section.
It should be fixed now.
